### ISSUE TITLE
Koodikatselmointi #2

### ISSUE THREAD

**Issue by henrima** [baobabKoodaa/Valhalla#1]
Ladattu 22.4. klo 18:28

Hieno simulaatio.

+++
- Selkeä rakenne ohjelmassa
- Kuvaavasti nimetyt luokat/metodit/muuttujat
- Hyvä testikattavuus
- Luontevasti mietityt testit muutenkin

---
- pari luokkaa (View.java ja Worm.java) olisi ehkä parin metodin osalta jaettavissa lyhyempiin ja sitä kautta selkeämpiin osiin

**Comment by autair** [comment]
Hei,

Miksiköhän mulle tulee palautetta jostain matopelistä (view.java ja  
worm.java luokista)? En tietääkseni ole tehnyt tai arvioinut mitään  
matopelejä...?

Aurora

Lainaus henrima <notifications@github.com>:

**Comment by baobabKoodaa** [comment]
Kiitos palautteesta. En itsekään ole tyytyväinen noihin pitkiin metodeihin.
